[tool.poetry]
name = "fave"
version = "2.0.1-dev"
description = "Forced alignment and vowel extraction"
authors = ["FAVE contributors"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
numpy = "^1.22"

[tool.poetry.dev-dependencies]
sphinx = "^4"
pylint = "^2.5.2"

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
